[package]
edition.workspace = true
name = "test-utils"
version.workspace = true

[dependencies]
clerk = { workspace = true, features = ["log"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
